apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: htmlpvc
spec:
   accessModes:
     - ReadWriteOnce
   resources:
       requests:
          storage: 10Gi
 
---
apiVersion: v1
kind: Pod
metadata:
    name: html-pod
    labels:
      app: html

spec:
      containers:
      - image: httpd
        name: html-cont
        
        
        volumeMounts:
        - name: html-persistent-storage
          mountPath: /usr/local/apache2/htdocs
      volumes:
      - name: html-persistent-storage
        persistentVolumeClaim:
          claimName: htmlpvc


---
apiVersion: v1
kind: Service
metadata:
  name: html-service
spec:
  type: NodePort
  selector:
    app: html
  ports:
    - nodePort: 31990
      port: 80
      targetPort: 80
